# action.yaml
name: 'Run a FastMCP Agent'
description: 'A GitHub Action that runs a FastMCP Agent'
inputs:
  package:
    description: 'Enter the name of the pypi package containing the agent'
    required: false
    default: "fastmcp-agents-library-agents"
  server_script:
    description: 'Enter pyproject.toml script for starting the FastMCP Agents server'
    required: true
  agent:
    description: 'Enter the agent name'
    required: true
  arguments:
    description: 'Enter the agent arguments'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  
  
    - name: "Install uv"
      uses: astral-sh/setup-uv@v3

    - name: "Create Configuration File"
      shell: bash
      run: |
        echo '{"mcpServers": {"agents": {"command": "uvx", "args": ["--with", "pydantic-ai@git+https://github.com/strawgate/pydantic-ai@dynamic-toolset","--from", "${{ inputs.package }}", "${{ inputs.server_script }}"]}}}' > "${{runner.temp}}/fastmcp-agent.json"
 
    - name: "Run the agent"
      shell: bash
      run: |
        uvx fastmcp-agents-cli call tool --config "${{runner.temp}}/fastmcp-agent.json" --tool ${{ inputs.agent }} --args '${{ inputs.arguments }}'
