name: Run a FastMCP Agent

on:
  issues:
    types: [opened]

jobs:
  run_fastmcp_agent:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run FastMCP Agent
        uses: ./
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODEL: "google-gla:gemini-2.5-flash"
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        with:
          package: "fastmcp-agents-library-agents"
          server_script: "github-triage"
          agent: "research_github_issue"
          arguments: '{"investigate_issue_number": ${{ github.event.issue.number }}, "investigate_issue_repo": "${{ github.event.repository.name }}", "investigate_issue_owner": "${{ github.repository_owner }}", "reply_to_issue_number": ${{ github.event.issue.number }}, "reply_to_issue_repo": "${{ github.event.repository.name }}", "reply_to_issue_owner": "${{ github.repository_owner }}"}'